<!-- FLOT CHART -->
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.canvaswrapper.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.colorhelpers.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.saturated.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.browser.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.drawSeries.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.uiConstants.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.time.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.resize.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.pie.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.crosshair.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.categories.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.navigate.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.touchNavigate.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.hover.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.touch.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.selection.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.symbol.js"></script>
<script src="<?= base_url(); ?>assets/plugins/flot/source/jquery.flot.legend.js"></script>